<table id="mage-activity-logs-datatable" class="table table-bordered table-hover display" style="width:100%">
    <thead>
        <tr>
            <th>@lang('backend.activity-logs.datatable.field.id')</th>
            <th>@lang('backend.activity-logs.datatable.field.user_id')</th>
            <th>@lang('backend.activity-logs.datatable.field.user_email')</th>
            <th>@lang('backend.activity-logs.datatable.field.model_type')</th>
            <th>@lang('backend.activity-logs.datatable.field.model_id')</th>
            <th>@lang('backend.activity-logs.datatable.field.uri')</th>
            <th>@lang('backend.activity-logs.datatable.field.action')</th>
            <th>@lang('backend.activity-logs.datatable.field.alias')</th>
            <th>@lang('backend.activity-logs.datatable.field.method')</th>
            <th>@lang('backend.activity-logs.datatable.field.user_agent')</th>
            <th>@lang('backend.activity-logs.datatable.field.ip_address')</th>
            <th>@lang('backend.activity-logs.datatable.field.created_at')</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
